export const ACTIONS = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  INCREMENT_QTY: 'INCREMENT_QTY',
  DECREMENT_QTY: 'DECREMENT_QTY',
  SET_CART_QTY: 'SET_CART_QTY',
  CLEAR_CART: 'CLEAR_CART',
  TOGGLE_WISHLIST: 'TOGGLE_WISHLIST',
  MOVE_WISHLIST_TO_CART: 'MOVE_WISHLIST_TO_CART',
  APPLY_PROMO: 'APPLY_PROMO',
  CLEAR_PROMO: 'CLEAR_PROMO',
  ADD_RECENT_VIEW: 'ADD_RECENT_VIEW',
  PLACE_ORDER: 'PLACE_ORDER',
  ADD_TOAST: 'ADD_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST'
};
